export const tools = [
  "Augenbinden", "Balltransport", "Catapult", "CollaborationPuzzle",
  "Complexity I", "Complexity II", "CultuRallye I", "CultuRallye II",
  "CultuRallye XXL I", "CultuRallye XXL II", "Band Mini I", "Band Mini II",
  "Band Mini III", "Band Standard I", "Band Standard II", "Band Standard III",
  "Band XXL I", "Band XXL II", "Band XXL III", "DominoEffect I",
  "DominoEffect II", "Spider-Rahmen", "Spider-Netz I", "Spider-Netz II",
  "Ecopoly", "EmotionCards 1 I", "EmotionCards 1 II", "EmotionCards 2",
  "EmotionCards DP", "FindMe", "Fliegender Teppich I",
  "Fliegender Teppich II", "Fliegender Teppich III", "FlottesRohr",
  "Fremde Welt I", "Fremde Welt II", "Fremde Welt III", "Future City I",
  "Future City II", "HeartSelling", "KommunikARTio I", "KommunikARTio II",
  "KommunikARTio III", "Leonardo's Bridge I", "Leonardo's Bridge II",
  "MagicNails I", "MagicNails II", "MetaBlog I", "MetaBlog II",
  "MetaBlog III", "MEBoard I", "MEBoard II", "MEBoard III", "MEBoard IV",
  "Moderationsbälle I", "Moderationsbälle II", "Pfadfinder I",
  "Pfadfinder II", "Pfadfinder III", "PerspActive I", "PerspActive II",
  "PerspActive III", "Pipeline I", "Pipeline II", "Pipeline III",
  "RealityCheck 1 I", "RealityCheck 1 II", "RealityCheck 2 I",
  "RealityCheck 2 II", "RealityCheck 2 III", "ScenarioCards 1 I",
  "ScenarioCards 1 II", "ScenarioCards 1 III", "ScenarioCards 1 IV",
  "ScenarioCards 1 V", "ScenarioCards 1 VI", "ScenarioCards 2 I",
  "ScenarioCards 2 II", "ScenarioCards 2 III", "ScenarioCards 2 IV",
  "ScenarioCards 2 V", "ScenarioCards 2 VI", "Seifenkiste I",
  "Seifenkiste II", "Seifenkiste III", "Seil 14m", "Seil 4m",
  "SmartMarble", "Stackman", "Stein der Weisen I", "Stein der Weisen II",
  "Stein der Weisen III", "Stein der Weisen IV", "Stein der Weisen V",
  "Stein der Weisen VI", "Stein der Weisen VII", "SysTeam I", "SysTeam II",
  "SysTeam III", "SysTeam IV", "Team² I", "Team² II", "Team² III",
  "Team² IV", "Team² V", "TeamNavigator I", "TeamNavigator II",
  "Tower of Power I", "Tower of Power II", "Tower of Power III",
  "Tower of Power IV", "Tower of Power V", "Tower of Power Mini",
  "Tower of Power Werte I", "Tower of Power Werte II", "Unmögliche Stäbe",
  "Verflixte Schlinge I", "Verflixte Schlinge II", "Verflixte Schlinge III",
  "Verflixte Schlinge IV", "Verflixte Schlinge V", "Verflixte Schlinge VI",
  "Verflixte Schlinge VII", "Verflixte Schlinge VIII",
  "Verflixte Schlinge IX", "Verflixte Schlinge X", "Verflixte Schlinge XI",
  "Wortspiel I", "Wortspiel II", "Zauberstab I", "Zauberstab II",
  "Zauberstab III", "Zauberstab IV", "Teambalken"
];

export const mitarbeiter = [
  "Nick",
  "Vincent",
  "Anna-Lena",
  "Allessandra",
  "Tamara",
  "Nino",
  "Lara",
  "Bastian",
  "Walter",
  "Tobi",
];
